### ISSUE TITLE
Shells hitting off target

### ISSUE THREAD

**Issue by Frey4cre** [Dreamfarer/ARMA-3-ARTILLERY-CALCULATOR-ARES#8]
Hello ! I got this issue on Arma 3 solo
I place my artillery, then my target. I use the exact elevation the website gave me.
But then when I watch the target it lands usually between 100-200m off the target.
Strange thing is when I go to KOTH and I use the same value it works. Since KOTH display a different elevation than the arma 3 one.
Last time I tried. The website said 26.02 elevation and I had to be at 24.09 to hit my target.
I am doing something wrong here ? I still don't understand why the value is correct with the koth hud but not with the arma one.
Thanks !

**Comment by Perytron** [comment]
Hey @FraP-zsz! 
Oh, that sounds familiar. I've tried to implement a solution, but failed miserably. Try testing it on an airfield or a generally not angled surface, I am quite sure it will work then because:

The KOTH Hud states the **_absolute_** angle of your gun, so it compensates for resting on a, e.g., steep hill. You can observe the difference in KOTH when comparing its HUD and the actual gun sight. As far as I know, the vanilla gun sight is **_relative_** to the ground, so e.g., if you rest on a 5° angled hill the calculcation will be off by 5°. 

I've tried to use the adjacent height data on the map to form a 3d plane which would tell me the tank's orientation in space. However, it gets really complicated once you also turn the turret around the yaw-axis while standing on an angled hill. I am not even sure if the height data could represent the orientation that accurately. Since many, including me, have only used it for KOTH, I've abandoned the idea because the HUD in KOTH will always be more accurate.
